### ISSUE TITLE
Props previously placed are disappearing when placing new props

### ISSUE THREAD

**Issue by Haneybd87** [yenyang/Anarchy-BepInEx#12]
For some reason this started happening today, before today it wasn't an issue. Now whenever I place new props it's making previously placed props disappear, most especially props previously placed using Anarchy but it's happening with other props to a lesser extent. The refresh props option doesn't seem to do anything (it didn't do anything before either) and reloading my save or the game doesn't seem to make them re-appear either. I saw there was a new version out yesterday so I tried installing that and it's not helping either. I really love the mod, it's really opened up my creative possibilities so I hope this is something you can do something about. Anyways thanks for the hard work.

**Comment by Haneybd87** [comment]
Looks like reloading an older save fixed the problem. Didn't lose too much progress at least. I'm still not sure why this suddenly happened. I will be testing it on every load just to make sure this doesn't happen again though.

**Comment by yenyang** [comment]
So two theories:
1. At some point you loaded the save without the Anarchy mod and saved. Doing this will lose all the history of what was placed with the anarchy toggle enabled.
2. Changes I made with  V1.2.1 are having some side effects. So I fixed a problem related to trees not being overridden when a growable building spawns, and cranes not being properly overridden. However, that fix also made it so that if you place a prop even with anarchy toggle enabled it will override other props if they weren't placed with anarchy toggle enabled. 

The refresh props button is unrelated to the issue were discussing. It's about prop culling which doesn't have to do with placement. It has more to do with zooming in and out.

**Comment by Haneybd87** [comment]
I’m having crashing issues that don’t seem to be mod related so I want to
reinstall the game. If I do this is there any specific files I should be
saving that have the anarchy history so this doesn’t happen afterward? Or
will just reinstalling the mod work?

**Comment by yenyang** [comment]
The history is packaged with the rest of the saved game file. You will need
to reinstall anarchy and reload the save with the mod.
