### ISSUE TITLE
Unfortunately, when I install this mod, I get an error as shown in the screenshot.

### ISSUE THREAD

**Issue by macros98** [yenyang/Anarchy-BepInEx#3]
![스크린샷 2023-12-30 023736](https://github.com/yenyang/Anarchy-BepInEx/assets/154670793/24a57894-b809-4d70-83b7-2d9c631d3354)

![스크린샷 2023-12-30 023814](https://github.com/yenyang/Anarchy-BepInEx/assets/154670793/890c1637-8624-4d9e-98d3-abf9f1029196)

![스크린샷 2023-12-30 023824](https://github.com/yenyang/Anarchy-BepInEx/assets/154670793/16a58c35-3bbf-45f0-9f0d-b1651ec2730e)

**Comment by yenyang** [comment]
How did you install the mod? Can you send me a screenshot of the folder the mod is installed at? You should have a ui.js file in there which is related to the problem you're having. It either cannot find that file or doesn't have access for some reason.

**Comment by macros98** [comment]
![스크린샷 2023-12-30 134040](https://github.com/yenyang/Anarchy-BepInEx/assets/154670793/53808794-a25f-4c7f-9e97-5b4d83f30842)

I put it in the "D:\Steam\steamapps\common\Cities Skylines II\BepInEx\plugins" folder as shown in the screenshot.

**Comment by yenyang** [comment]
Please delete everything, then redownload/unzip everything, but this time keep each mod separate in it's own folder within the plugins folder. ...plugins/Anarchy/... and ... plugins/Tree_Controller/... and ...plugins/Extended_Road_Upgrades/... etc. 
The problem is that Anarchy and Tree Controller both have a file called ui.js and when you installed Tree Controller you overwrote the ui.js file for Anarchy.

**Comment by yenyang** [comment]
The actual name of the folders probably doesn't matter, but keep each mod seperate.

**Comment by macros98** [comment]
The correct way would be to designate each mode as a separate folder. Thank you.
